Repository fictadvisor/fictadvisor-web, pull requests merged in 2023-07, with the labels that each got.

#489 feature/seo-tags
  src/components/common/layout/page-layout/PageLayout.tsx
  src/components/pages/404-page/NotFoundPage.tsx
  src/components/pages/account-page/AccountPage.tsx
  src/components/pages/account-page/components/group-tab/components/table/student-table/StudentsTable.tsx
  src/components/pages/login-page/LoginPage.tsx
  src/components/pages/main-page/MainPage.module.scss
  src/components/pages/main-page/MainPage.tsx
  src/components/pages/password-recovery/create-password-page/CreatePasswordPage.tsx
  src/components/pages/password-recovery/email-confirmation-page/PasswordResetEmailConfirmationPage.tsx
  src/components/pages/password-recovery/forgot-password-page/ForgotPasswordPage.tsx
  src/components/pages/password-recovery/link-expired/PasswordResetLinkExpiredPage.tsx
  src/components/pages/password-recovery/link-valid/PasswordResetValidLinkPage.tsx
  src/components/pages/personal-teacher-page/PersonalTeacherPage.tsx
  src/components/pages/personal-teacher-subject-page/PersonalTeacherSubjectPage.tsx
  src/components/pages/poll-page/PollPage.tsx
  src/components/pages/privacy-page/PrivacyPage.module.scss
  src/components/pages/privacy-page/PrivacyPage.tsx
  src/components/pages/register/email-confirmation-page/RegistrationEmailConfirmationPage.tsx
  src/components/pages/register/register-page/RegisterPage.tsx
  src/components/pages/register/verify-email-token-page/VerifyEmailTokenPage.tsx
  src/components/pages/search-pages/poll-teachers-page/PollTeacherPage.tsx
  src/components/pages/search-pages/subject-search/SubjectSearchPage.tsx
  src/components/pages/search-pages/subject-teacher-search/SubjectTeacherPage.tsx
  src/components/pages/search-pages/teacher-search/TeacherSearchPage.tsx
  src/pages/404.tsx
  src/pages/account.tsx
  src/pages/discipline.tsx
  src/pages/login.tsx
  src/pages/password-recovery/[token].tsx
  src/pages/password-recovery/email-verification.tsx
  src/pages/password-recovery/index.tsx
  src/pages/password-recovery/invalid.tsx
  src/pages/password-recovery/valid.tsx
  src/pages/poll/[disciplineTeacherId].tsx
  src/pages/poll/index.ts
  src/pages/poll/index.tsx
  src/pages/privacy.tsx
  src/pages/register/email-verification/[token].tsx
  src/pages/register/email-verification/index.tsx
  src/pages/register/index.tsx
  src/pages/subjects/[subjectId]/teachers.tsx
  src/pages/subjects/index.tsx
  src/pages/teachers/[teacherId].tsx
  src/pages/teachers/index.tsx
Labels: feature

#534 fix : not-working-password-recovery (`#527`)
  src/components/pages/password-recovery/forgot-password-page/components/forgot-password-form/ForgotPasswordForm.tsx
Labels: bugfix

#552 feature: fly in a navbar
  public/icons/fly-logo.svg
  src/components/common/layout/footer/Footer.tsx
  src/components/common/layout/header/components/desktop-header/DesktopHeader.tsx
  src/components/common/layout/header/components/mobile-header/MobileHeader.tsx
Labels: feature

#551 enhancement:mui-tables & no-group section bug
  src/components/common/ui/icon-button-mui/IconButton.tsx
  src/components/pages/account-page/components/group-tab/GroupTab.tsx
  src/components/pages/account-page/components/group-tab/components/table/grid.styles.ts
  src/components/pages/account-page/components/group-tab/components/table/mobile-requests-table/MobileRequestsTable.module.scss
  src/components/pages/account-page/components/group-tab/components/table/mobile-requests-table/MobileRequestsTable.tsx
  src/components/pages/account-page/components/group-tab/components/table/mobile-requests-table/index.ts
  src/components/pages/account-page/components/group-tab/components/table/mobile-students-table/MobileStudentsTable.module.scss
  src/components/pages/account-page/components/group-tab/components/table/mobile-students-table/MobileStudentsTable.tsx
  src/components/pages/account-page/components/group-tab/components/table/mobile-students-table/components/mobile-students-table-buttons/MobileStudentsTableButtons.module.scss
  src/components/pages/account-page/components/group-tab/components/table/mobile-students-table/components/mobile-students-table-buttons/MobileStudentsTableButtons.tsx
  src/components/pages/account-page/components/group-tab/components/table/mobile-students-table/components/mobile-students-table-buttons/index.ts
  src/components/pages/account-page/components/group-tab/components/table/mobile-students-table/index.ts
  src/components/pages/account-page/components/group-tab/components/table/requests-table/RequestTable.styles.ts
  src/components/pages/account-page/components/group-tab/components/table/requests-table/RequestsTable.module.scss
  src/components/pages/account-page/components/group-tab/components/table/requests-table/RequestsTable.tsx
  src/components/pages/account-page/components/group-tab/components/table/student-table/StudentsTable.module.scss
  src/components/pages/account-page/components/group-tab/components/table/student-table/StudentsTable.styles.ts
  src/components/pages/account-page/components/group-tab/components/table/student-table/StudentsTable.tsx
  src/components/pages/account-page/components/group-tab/components/table/student-table/components/EditingColumn.tsx
  src/components/pages/account-page/components/group-tab/components/table/student-table/components/MobileDropdown.style.ts
  src/components/pages/account-page/components/group-tab/components/table/student-table/components/MobileDropdown.tsx
  src/components/pages/account-page/components/group-tab/components/text-area-popup/TextAreaPopup.module.scss
  src/components/pages/account-page/components/group-tab/components/text-area-popup/TextAreaPopup.styles.ts
  src/components/pages/account-page/components/group-tab/components/text-area-popup/TextAreaPopup.tsx
Labels: bugfix, enhancement

#554 + rating to floating card
  src/components/common/ui/cards/floating-card/FloatingCard.tsx
Labels: bugfix

#585 fix/scrolling-on-open-popup
  src/components/common/ui/pop-ups-mui/Popup/Popup.styles.ts
  src/components/common/ui/pop-ups-mui/Popup/Popup.tsx
  src/styles/global-styles.scss
Labels: bugfix

#586 enhancement/subject-search-page-and-card-mui
  src/components/common/ui/cards/subject-card/SubjectCard.module.scss
  src/components/common/ui/cards/subject-card/SubjectCard.styles.ts
  src/components/common/ui/cards/subject-card/SubjectCard.tsx
  src/components/pages/search-pages/poll-teachers-page/PollTeacherPage.module.scss
  src/components/pages/search-pages/poll-teachers-page/PollTeacherPage.tsx
  src/components/pages/search-pages/poll-teachers-page/components/PollTeacherSearchList.module.scss
  src/components/pages/search-pages/poll-teachers-page/components/PollTeacherSearchList.styles.ts
  src/components/pages/search-pages/poll-teachers-page/components/PollTeacherSearchList.tsx
  src/components/pages/search-pages/search-form/SearchForm.module.scss
  src/components/pages/search-pages/search-form/SearchForm.tsx
  src/components/pages/search-pages/subject-search/SubjectSearchList.module.scss
  src/components/pages/search-pages/subject-search/SubjectSearchPage.styles.ts
  src/components/pages/search-pages/subject-search/SubjectSearchPage.tsx
  src/components/pages/search-pages/subject-search/components/SubjectSearchList.styles.ts
  src/components/pages/search-pages/subject-search/components/SubjectSearchList.tsx
  src/components/pages/search-pages/subject-search/components/constants/breakpoints.tsx
  src/components/pages/search-pages/subject-teacher-search/SearchTeacherPage.module.scss
  src/components/pages/search-pages/subject-teacher-search/SearchTeacherPage.tsx
  src/components/pages/search-pages/subject-teacher-search/components/SubjectTeacherSearchList.module.scss
  src/components/pages/search-pages/subject-teacher-search/components/SubjectTeacherSearchList.styles.ts
  src/components/pages/search-pages/subject-teacher-search/components/SubjectTeacherSearchList.tsx
  src/components/pages/search-pages/subject-teacher-search/index.ts
  src/components/pages/search-pages/teacher-search/TeacherSearchPage.module.scss
  src/components/pages/search-pages/teacher-search/TeacherSearchPage.tsx
  src/components/pages/search-pages/teacher-search/components/TeacherSearchList.module.scss
  src/components/pages/search-pages/teacher-search/components/TeacherSearchList.tsx
Labels: enhancement

#591 fix/teacher-cards
  src/components/common/ui/cards/poll-teacher-card/PollTeacherCard.module.scss
Labels: bugfix

#450 feature: Schedule input
  src/components/common/ui/schedule-input/ScheduleInput.styles.ts
  src/components/common/ui/schedule-input/ScheduleInput.tsx
  src/components/common/ui/schedule-input/index.ts
  src/components/pages/test-pages/schedule-input/ScheduleInputPage.styles.ts
  src/components/pages/test-pages/schedule-input/ScheduleInputPage.tsx
  src/components/pages/test-pages/schedule-input/index.ts
  src/pages/test/schedule-input.tsx
Labels: feature

#467 feature/create-schedule-cards
  src/components/common/ui/arrow-button/ArrowButton.module.scss
  src/components/common/ui/arrow-button/ArrowButton.tsx
  src/components/common/ui/arrow-button/index.ts
  src/components/common/ui/schedule-card/ScheduleCard.styles.ts
  src/components/common/ui/schedule-card/ScheduleCard.tsx
  src/components/common/ui/schedule-card/index.ts
  src/components/common/ui/schedule-card/types/index.ts
  src/components/common/ui/schedule-card/utils/calculateHeight.ts
  src/components/pages/poll-page/components/answers-sheet/AnswersSheet.tsx
  src/components/pages/test-pages/schedule-card-page/ScheduleCardPage.styles.ts
  src/components/pages/test-pages/schedule-card-page/ScheduleCardPage.tsx
  src/components/pages/test-pages/schedule-card-page/index.ts
  src/pages/test/schedule-card.tsx
  src/styles/theme/constants/pallete/palette.ts
Labels: feature

#558 enhancement/mui-teacher-card
  src/components/common/ui/cards/personal-teacher-card/PersonalTeacherCard.styles.ts
  src/components/common/ui/cards/personal-teacher-card/PersonalTeacherCard.tsx
  src/components/common/ui/cards/personal-teacher-card/index.ts
  src/components/pages/personal-teacher-page/PersonalTeacherPage.tsx
  src/components/pages/personal-teacher-page/contacts/Contact.tsx
  src/components/pages/personal-teacher-page/personal-teacher-card/PersonalTeacherCard.module.scss
  src/components/pages/personal-teacher-page/personal-teacher-card/PersonalTeacherCard.tsx
Labels: enhancement
