Repository fictadvisor/fictadvisor-web, pull requests merged in 2023-06, with the labels that each got.

#346 fix/buttons-svg
  src/components/common/ui/button-mui/Button.styles.ts
  src/components/common/ui/icon-button-mui/IconButton.styles.ts
  src/components/common/ui/icon-button-mui/variants/ArrowButton/ArrowButton.styles.ts
Labels: bugfix

#406 enhancement/ssg-register-page
  src/components/pages/register/register-page/RegisterPage.tsx
  src/pages/register/index.tsx
Labels: enhancement

#405 enhancement/next-link
  src/components/common/layout/header/components/mobile-header/components/drawer/Drawer.tsx
  src/components/common/ui/breadcrumbs/Breadcrumbs.tsx
  src/components/common/ui/link/Link.tsx
  src/components/pages/password-recovery/email-confirmation-page/components/send-again-link/Link.module.scss
  src/components/pages/password-recovery/email-confirmation-page/components/send-again-link/Link.tsx
  src/components/pages/password-recovery/email-confirmation-page/components/send-again-link/index.ts
  src/components/pages/personal-teacher-page/contacts/Contact.tsx
  src/components/pages/personal-teacher-subject-page/contacts/Contact.tsx
  src/components/pages/register/email-confirmation-page/components/send-again-link/Link.module.scss
  src/components/pages/register/email-confirmation-page/components/send-again-link/Link.tsx
  src/components/pages/register/email-confirmation-page/components/send-again-link/index.ts
Labels: enhancement

#436 fix/missing-padding
  src/components/pages/personal-teacher-page/personal-teacher-card/PersonalTeacherCard.module.scss
  src/components/pages/personal-teacher-page/personal-teacher-card/PersonalTeacherCard.tsx
  src/components/pages/personal-teacher-subject-page/personal-teacher-subject-card/PersonalTeacherSubjectCard.module.scss
  src/components/pages/personal-teacher-subject-page/personal-teacher-subject-card/PersonalTeacherSubjectCard.tsx
Labels: bugfix

#409 enhancement/mui-tab-pages
  src/components/common/ui/tab/index.ts
  src/components/common/ui/tab/tab-item/TabItem.module.scss
  src/components/common/ui/tab/tab-item/TabItem.tsx
  src/components/common/ui/tab/tab-list/TabList.tsx
  src/components/common/ui/tab/tab-panel/TabPanel.tsx
  src/components/common/ui/tab/tab-panels-list/TabPanelsList.tsx
  src/components/pages/account-page/AccountPage.module.scss
  src/components/pages/account-page/AccountPage.styles.ts
  src/components/pages/account-page/AccountPage.tsx
Labels: enhancement

#445 changed max value on several charts + set max ticks count for charts
  src/components/common/ui/column-chart/ColumnChart.tsx
  src/components/common/ui/column-chart/utils/options.ts
  src/components/pages/personal-teacher-page/personal-teacher-tabs/components/general-tab/GeneralTab.tsx
Labels: bugfix

#444 rewrited main page to ssg
  src/components/pages/main-page/MainPage.tsx
  src/pages/index.tsx
Labels: enhancement

#428 enhancement/mui-dropdown-implementation
  src/components/common/ui/form/dropdown-mui/Dropdown.tsx
  src/components/common/ui/form/dropdown/Dropdown.module.scss
  src/components/common/ui/form/dropdown/Dropdown.styles.tsx
  src/components/common/ui/form/dropdown/Dropdown.tsx
  src/components/common/ui/form/dropdown/Option.tsx
  src/components/common/ui/form/dropdown/index.ts
  src/components/pages/account-page/components/group-tab/components/no-group-block/NoGroupBlock.tsx
  src/components/pages/register/register-page/components/register-form/RegisterForm.tsx
  src/components/pages/search-pages/search-form/SearchForm.tsx
  src/components/pages/test-pages/dropdown/dropdownTestPage.tsx
  src/pages/test/dropdown.tsx
Labels: enhancement

#446 enhancement/legacy-textarea
  src/components/common/ui/form/index.ts
  src/components/common/ui/form/text-area-mui/TextArea.tsx
  src/components/common/ui/form/text-area-mui/index.ts
  src/components/pages/poll-page/components/answers-sheet/AnswerSheet.style.ts
  src/components/pages/poll-page/components/answers-sheet/AnswersSheet.module.scss
  src/components/pages/poll-page/components/answers-sheet/AnswersSheet.tsx
  src/components/pages/poll-page/components/answers-sheet/constants/index.ts
  src/components/pages/test-pages/text-area-page/TextAreaPage.tsx
Labels: enhancement

#454 feature/poll-card-skip-button
  next.config.js
  src/components/common/ui/cards/poll-teacher-card/PollTeacherCard.module.scss
  src/components/common/ui/cards/poll-teacher-card/PollTeacherCard.tsx
  src/components/common/ui/cards/poll-teacher-card/SkipTeacherPopup.tsx
  src/components/common/ui/cards/poll-teacher-card/pollTeachaerCard.styles.ts
  src/components/pages/search-pages/poll-teachers-page/PollTeacherSearchList.tsx
  src/lib/api/teacher/TeacherAPI.ts
Labels: feature

#332 enhancement/slider-mui
  src/components/common/ui/form/slider-mui/Slider.styles.ts
  src/components/common/ui/form/slider-mui/Slider.tsx
  src/components/common/ui/form/slider-mui/const/marks.ts
  src/components/common/ui/form/slider-mui/index.ts
  src/components/pages/test-pages/slider-page/SliderPage.styles.ts
  src/components/pages/test-pages/slider-page/SliderPage.tsx
  src/pages/test/slider.tsx
Labels: enhancement

#469 fix:cross-button-alignment
  src/components/common/ui/cards/poll-teacher-card/pollTeachaerCard.styles.ts
Labels: bugfix

#440 added floating card
  src/components/common/composite/cards/floating-card/FloatingCard.styles.tsx
  src/components/common/composite/cards/floating-card/FloatingCard.tsx
  src/components/common/composite/cards/floating-card/index.ts
  src/components/pages/personal-teacher-page/PersonalTeacherPage.tsx
  src/components/pages/personal-teacher-page/personal-teacher-card/PersonalTeacherCard.tsx
  src/components/pages/personal-teacher-page/personal-teacher-tabs/components/comment-tab/CommentTab.styles.ts
  src/components/pages/personal-teacher-page/personal-teacher-tabs/components/comment-tab/CommentTab.tsx
  src/components/pages/personal-teacher-subject-page/PersonalTeacherSubjectPage.tsx
  src/components/pages/personal-teacher-subject-page/personal-teacher-subject-card/PersonalTeacherSubjectCard.tsx
Labels: feature

#479 fix/cards-lines
  src/components/pages/personal-teacher-page/personal-teacher-card/PersonalTeacherCard.module.scss
  src/components/pages/personal-teacher-subject-page/personal-teacher-subject-card/PersonalTeacherSubjectCard.module.scss
Labels: bugfix

#491 fix/subject-teacher-card-cuts-off
  src/components/common/ui/cards/subject-teacher-card/SubjectTeacherCard.module.scss
Labels: bugfix

#495 fix/comment-cuts-off
  src/components/common/ui/form/text-area-mui/TextArea.tsx
Labels: bugfix

#382 enhancement/mui-link
  src/components/common/ui/link-mui/Link.styles.ts
  src/components/common/ui/link-mui/Link.tsx
  src/components/common/ui/link-mui/index.ts
  src/components/pages/test-pages/mui-link-page/MUILinkPage.tsx
  src/components/pages/test-pages/mui-link-page/index.ts
  src/pages/test/link.tsx
Labels: enhancement

#502 fix:locale storage dropdown bug (#500)
  src/components/common/ui/form/dropdown/Dropdown.tsx
  src/components/pages/register/register-page/components/register-form/constants/index.ts
  src/components/pages/search-pages/search-form/SearchForm.tsx
  src/components/pages/search-pages/teacher-search/TeacherSearchPage.tsx
Labels: bugfix

#509 feature/selection-text
  src/styles/global-styles.scss
Labels: feature

#510 fix: no comments on empty dropdown (#508)
  src/components/common/ui/form/dropdown/Dropdown.tsx
  src/components/pages/personal-teacher-page/personal-teacher-tabs/components/comment-tab/CommentTab.tsx
Labels: bugfix
