Repository fictadvisor/fictadvisor-web, pull requests merged in 2023-11, with the labels that each got.

#828 bugfix/fix-change-role-button
  src/components/pages/account-page/components/group-tab/components/table/student-table/components/EditingColumn.tsx
Labels: bugfix

#827 Bugfix/typos
  src/components/common/ui/cards/poll-teacher-card/SkipTeacherPopup.tsx
  src/components/pages/account-page/components/group-tab/components/table/student-table/components/EditingColumn.tsx
  src/components/pages/account-page/components/security-tab/SecurityTab.tsx
  src/components/pages/account-page/components/security-tab/components/change-password-form/ChangePasswordForm.tsx
  src/components/pages/contract-admin-page/utils/index.ts
  src/components/pages/contract-page/components/personal-form/PersonalForm.tsx
  src/components/pages/contract-page/components/steps/FirstStep.tsx
  src/components/pages/email-confirmation-page/EmailConfirmationPage.tsx
  src/components/pages/entrant-dashboard-page/EntrantDashboardPage.tsx
  src/components/pages/entrant-dashboard-page/components/PersonalDataSection.tsx
  src/components/pages/entrant-dashboard-page/components/PrioritiesSection.tsx
  src/components/pages/entrant-dashboard-page/components/entrant-approve-form/ContractApproveForm.tsx
  src/components/pages/entrant-dashboard-page/components/entrant-search-form/EntrantSearchForm.tsx
  src/components/pages/main-page/MainPage.tsx
  src/components/pages/password-recovery/forgot-password-page/ForgotPasswordPage.tsx
  src/components/pages/priority-approve-page/utils/checkError.ts
  src/hooks/use-toast-error/useToastError.tsx
  src/pages/poll/[disciplineTeacherId].tsx
  src/pages/subjects/index.tsx
  src/pages/teachers/index.tsx
Labels: bugfix

#831 bugfix/password-recovery-text
  src/components/pages/email-confirmation-page/EmailConfirmationPage.tsx
Labels: bugfix

#836 feature/admin-menu-panel
  src/components/common/layout/admin-panel-layout/AdminPanelLayout.styles.ts
  src/components/common/layout/admin-panel-layout/AdminPanelLayout.tsx
  src/components/common/layout/admin-panel/AdminPanel.styles.ts
  src/components/common/layout/admin-panel/AdminPanel.tsx
  src/components/common/layout/admin-panel/constants/index.tsx
  src/components/common/layout/page-layout/PageLayout.tsx
  src/pages/admin/departments/create.tsx
  src/pages/admin/departments/edit/[departmentId].tsx
  src/pages/admin/departments/index.tsx
  src/pages/admin/disciplines/create.tsx
  src/pages/admin/disciplines/edit/[disciplineId].tsx
  src/pages/admin/disciplines/index.tsx
  src/pages/admin/groups/create.tsx
  src/pages/admin/groups/edit/[groupId].tsx
  src/pages/admin/groups/index.tsx
  src/pages/admin/index.tsx
  src/pages/admin/rights/create.tsx
  src/pages/admin/rights/edit/[rightId].tsx
  src/pages/admin/rights/index.tsx
  src/pages/admin/roles/create.tsx
  src/pages/admin/roles/edit/[roleId].tsx
  src/pages/admin/roles/index.tsx
  src/pages/admin/students/create.tsx
  src/pages/admin/students/edit/[studentId].tsx
  src/pages/admin/students/index.tsx
  src/pages/admin/subjects/create.tsx
  src/pages/admin/subjects/edit/[subjectId].tsx
  src/pages/admin/subjects/index.tsx
  src/pages/admin/teachers/create.tsx
  src/pages/admin/teachers/edit/[teacherId].tsx
  src/pages/admin/teachers/index.tsx
  src/pages/admin/users/create.tsx
  src/pages/admin/users/edit/[userId].tsx
  src/pages/admin/users/index.tsx
Labels: feature

#754 enhancement/add-missing-UserApi-endpoints
  src/lib/api/user/UserAPI.ts
  src/lib/api/user/types/ChangeRoleBody.ts
  src/lib/api/user/types/GetSelectiveResponse.ts
  src/lib/api/user/types/PostSuperheroBody.ts
  src/lib/api/user/types/VerifyStudentBody.ts
  src/lib/api/user/types/VerifySuperheroBody.ts
Labels: enhancement

#842 bugfix/contact-validation
  src/components/pages/account-page/components/general-tab/components/contacts-block/validation/index.ts
Labels: bugfix

#847 seo/schedule-page-description
  src/components/pages/schedule-page/SchedulePage.tsx
Labels: SEO

#845 bugfix/header-design
  src/components/common/layout/header/Header.tsx
Labels: bugfix

#843 feature/main-admin-page
  src/components/common/layout/admin-panel/AdminPanel.tsx
  src/components/common/layout/admin-panel/constants/index.tsx
  src/components/pages/admin/admin-default/AdminMainPage.styles.ts
  src/components/pages/admin/admin-default/AdminMainPage.tsx
  src/components/pages/admin/admin-default/index.ts
  src/components/pages/admin/main-page/create/index.tsx
  src/components/pages/admin/main-page/edit/index.tsx
  src/components/pages/admin/main-page/index.tsx
  src/components/pages/main-page/MainPage.tsx
  src/components/pages/main-page/completely-normal-folder/GreetingBlock.tsx
  src/pages/admin/index.tsx
  src/styles/global-styles.scss
Labels: feature

#825 bugfix/scroll-up-button
  src/components/pages/schedule-page/calendar-section/components/mobile/buttonIcons/buttonIcons.styles.ts
Labels: bugfix

#852 bugfix/schedule-checkbox
  src/components/pages/schedule-page/SchedulePage.tsx
  src/components/pages/schedule-page/calendar-section/components/checkboxes-section/CheckBoxSection.tsx
  src/store/schedule/useSchedule.ts
Labels: bugfix

#862 Fixed wrong first day calculation
  src/components/pages/main-page/MainPage.tsx
  src/store/schedule/utils/getFirstDayOfAWeek.ts
Labels: bugfix

#879 👩‍🏫 teacher sorting issue
  src/components/pages/search-pages/search-form/SearchForm.tsx
Labels: bug

#876 bugfix/user-profile-pic
  src/components/pages/account-page/components/group-tab/components/table/grid.styles.ts
  src/components/pages/account-page/components/group-tab/components/table/student-table/StudentsTable.tsx
Labels: bug
