Repository fictadvisor/fictadvisor-web, pull requests merged in 2023-02, with the labels that each got.

#132 fix/arrow-buttons
  src/components/common/ui/arrow-button/ArrowButton.module.scss
  src/components/common/ui/arrow-button/ArrowButton.tsx
  src/components/common/ui/arrow-button/index.ts
  src/components/pages/test-pages/arrows-page/ArrowButton.module.scss
  src/components/pages/test-pages/arrows-page/ArrowsPage.tsx
Labels: enhancement, ui kit

#130 fix/tag-refactoring
  src/components/common/composite/cards/Cards.tsx
  src/components/common/ui/tag/Tag.module.scss
  src/components/common/ui/tag/Tag.tsx
  src/components/common/ui/tag/index.ts
  src/components/pages/test-pages/tables-page/TablesPage.tsx
  src/components/pages/test-pages/tags-page/TagsPage.tsx
Labels: enhancement, ui kit

#129 Added all Button Icons
  src/components/common/ui/icon-button/IconButton.module.scss
  src/components/common/ui/icon-button/IconButton.tsx
  src/components/common/ui/icon-button/index.ts
  src/components/common/ui/icon-button/variants/CloseButton.tsx
  src/components/common/ui/icon-button/variants/SortButton.tsx
  src/components/common/ui/icon-button/variants/StarButton.tsx
  src/components/common/ui/icon-button/variants/TrashBucketButton.tsx
  src/components/common/ui/icon-button/variants/index.ts
  src/components/pages/test-pages/icon-buttons-page/IconButtonsPage.tsx
  src/components/pages/test-pages/tables-page/TablesPage.tsx
Labels: feature, ui kit

#136 packages/update-ubuntu
  .github/workflows/build.yml
Labels: bug

#135 fix/alert-refactoring
  src/components/common/ui/alert-block/AlertBlock.module.scss
  src/components/common/ui/alert-block/AlertBlock.tsx
  src/components/common/ui/alert-block/index.ts
  src/components/common/ui/alert/Alert.module.scss
  src/components/common/ui/alert/Alert.tsx
  src/components/common/ui/alert/index.ts
  src/components/pages/test-pages/alerts-page/AlertsPage.tsx
Labels: enhancement, ui kit

#128 fix/controls-refactoring
  .eslintrc.json
  public/assets/icons/check-mark.svg
  src/components/common/ui/check/Check.tsx
  src/components/common/ui/check/index.ts
  src/components/common/ui/checkbox/Checkbox.module.scss
  src/components/common/ui/checkbox/Checkbox.tsx
  src/components/common/ui/checkbox/index.ts
  src/components/common/ui/group-radio/GroupRadioProps.tsx
  src/components/common/ui/group-radio/index.ts
  src/components/common/ui/radio-group/RadioGroup.module.scss
  src/components/common/ui/radio-group/RadioGroup.tsx
  src/components/common/ui/radio-group/index.ts
  src/components/common/ui/switch/Switch.module.scss
  src/components/common/ui/switch/Switch.tsx
  src/components/common/ui/switch/index.ts
  src/components/pages/login-page/LoginPage.tsx
  src/components/pages/test-pages/controls-page/ControlsPage.tsx
  src/components/pages/test-pages/tables-page/TablesPage.tsx
Labels: feature, ui kit

#137 fix/buttons
  src/components/common/composite/cards/Cards.tsx
  src/components/common/custom-svg/CustomCheck.tsx
  src/components/common/ui/alert-button/AlertButton.module.scss
  src/components/common/ui/alert-button/AlertButton.tsx
  src/components/common/ui/alert-button/index.ts
  src/components/common/ui/button/Button.module.scss
  src/components/common/ui/button/Button.tsx
  src/components/common/ui/button/index.ts
  src/components/common/ui/button/styles/button-style.scss
  src/components/common/ui/button/styles/primary.scss
  src/components/common/ui/button/styles/secondary.scss
  src/components/common/ui/button/styles/tertiary.scss
  src/components/pages/login-page/LoginPage.tsx
  src/components/pages/test-pages/alert-buttons-page/AlertButtonsPage.tsx
  src/components/pages/test-pages/buttons-page/ButtonsPage.tsx
  src/components/pages/test-pages/tables-page/TablesPage.tsx
Labels: enhancement, ui kit

#154 Feature/popup
  src/components/common/composite/popup/Popup.module.scss
  src/components/common/composite/popup/Popup.tsx
  src/components/common/composite/popup/index.ts
  src/components/common/layout/footer/Footer.tsx
  src/components/common/layout/header/Header.module.scss
  src/components/common/layout/header/Header.tsx
  src/components/common/layout/header/components/header-mobile-card/HeaderMobileCard.module.scss
  src/components/pages/test-pages/popup-page/PopupPage.tsx
  src/components/pages/test-pages/popup-page/index.ts
  src/pages/test/popup.tsx
Labels: ui kit

#164 feture/pages
  src/components/common/custom-svg/CustomEnvelopeOpen.tsx
  src/components/common/custom-svg/CustomShield.tsx
  src/components/common/layout/page-layout/PageLayout.module.scss
  src/components/pages/create-password-page/CreatePasswordPage.module.scss
  src/components/pages/create-password-page/CreatePasswordPage.tsx
  src/components/pages/create-password-page/components/create-password-form/CreatePasswordForm.tsx
  src/components/pages/create-password-page/components/create-password-form/constants/index.ts
  src/components/pages/create-password-page/components/create-password-form/index.ts
  src/components/pages/create-password-page/components/create-password-form/types/index.ts
  src/components/pages/create-password-page/components/create-password-form/validation/index.ts
  src/components/pages/create-password-page/index.ts
  src/components/pages/forgot-password-page/ForgotPasswordPage.module.scss
  src/components/pages/forgot-password-page/ForgotPasswordPage.tsx
  src/components/pages/forgot-password-page/components/forgot-password-form/ForgotPasswordForm.tsx
  src/components/pages/forgot-password-page/components/forgot-password-form/constants/index.ts
  src/components/pages/forgot-password-page/components/forgot-password-form/index.ts
  src/components/pages/forgot-password-page/components/forgot-password-form/types/index.ts
  src/components/pages/forgot-password-page/components/forgot-password-form/validation/index.ts
  src/components/pages/forgot-password-page/index.ts
  src/components/pages/registration-email-confirmation-page/RegistrationEmailConfirmationPage.module.scss
  src/components/pages/registration-email-confirmation-page/RegistrationEmailConfirmationPage.tsx
  src/components/pages/registration-email-confirmation-page/components/send-again-link/Link.module.scss
  src/components/pages/registration-email-confirmation-page/components/send-again-link/Link.tsx
  src/components/pages/registration-email-confirmation-page/components/send-again-link/index.ts
  src/components/pages/reset-password-email-confirmation/PasswordResetEmailConfirmationPage.module.scss
  src/components/pages/reset-password-email-confirmation/PasswordResetEmailConfirmationPage.tsx
  src/components/pages/reset-password-email-confirmation/components/send-again-link/Link.module.scss
  src/components/pages/reset-password-email-confirmation/components/send-again-link/Link.tsx
  src/components/pages/reset-password-email-confirmation/components/send-again-link/index.ts
  src/components/pages/reset-password-link-expired/PasswordResetLinkExpiredPage.module.scss
  src/components/pages/reset-password-link-expired/PasswordResetLinkExpiredPage.tsx
  src/components/pages/reset-password-valid-link/PasswordResetValidLinkPage.module.scss
  src/components/pages/reset-password-valid-link/PasswordResetValidLinkPage.tsx
  src/pages/password-recovery/[token].tsx
  src/pages/password-recovery/index.tsx
  src/styles/partials/_typography-mixins.scss
Labels: page
