Repository fictadvisor/fictadvisor-web, pull requests merged in 2023-09, with the labels that each got.

#666 bugfix/icon-button-props
  src/components/common/ui/icon-button-mui/variants/ArrowButton/ArrowButton.tsx
  src/components/common/ui/icon-button-mui/variants/CloseButton/CloseButton.tsx
  src/components/common/ui/icon-button-mui/variants/SortButton/SortButton.tsx
  src/components/common/ui/icon-button-mui/variants/StarButton/StarButton.tsx
  src/components/common/ui/icon-button-mui/variants/TrashBucketButton/TrashBucketButton.tsx
Labels: bugfix

#660 bugfix/register-page-layout-on-small-screen
  src/components/common/ui/form/checkbox/Checkbox.styles.ts
  src/components/pages/login-page/components/login-form-block/LoginFormBlock.styles.ts
  src/components/pages/register/register-page/RegisterPage.styles.ts
Labels: bugfix

#671 bugfix/masonri-break
  src/components/common/ui/cards/subject-card/SubjectCard.styles.ts
Labels: bugfix

#412 enhancement: new Input-mui
  src/components/common/ui/form/input-mui/Input.stories.tsx
  src/components/common/ui/form/input-mui/Input.styles.ts
  src/components/common/ui/form/input-mui/Input.tsx
  src/components/common/ui/form/input-mui/constants/index.ts
  src/components/common/ui/form/input-mui/index.ts
  src/components/common/ui/form/input-mui/types/index.ts
  src/components/common/ui/form/input-mui/util/index.ts
  src/components/common/ui/form/with-formik/input/FormikInput.stories.tsx
  src/components/common/ui/form/with-formik/input/FormikInput.tsx
  src/components/common/ui/form/with-formik/input/index.ts
  src/components/common/ui/immutable-input/ImmutableInput.module.scss
  src/components/common/ui/immutable-input/ImmutableInput.tsx
  src/components/common/ui/immutable-input/index.ts
  src/components/pages/account-page/components/general-tab/components/contacts-block/components/ContactItem.tsx
  src/components/pages/account-page/components/security-tab/SecurityTab.tsx
Labels: enhancement, documentation

#653 feature-bugfix/add-discord-fix-footer (#498)
  src/components/common/icons/Discord.tsx
  src/components/common/layout/footer/Footer.styles.ts
  src/components/common/layout/footer/constants/index.tsx
  src/components/pages/search-pages/subject-search/SubjectSearchPage.tsx
Labels: bugfix, feature

#687 answers-saved-mui
  src/components/pages/poll-page/components/answers-sheet/AnswersSaved/AnswerSaved.style.ts
  src/components/pages/poll-page/components/answers-sheet/AnswersSaved/AnswersSaved.module.scss
  src/components/pages/poll-page/components/answers-sheet/AnswersSaved/AnswersSaved.tsx
Labels: enhancement

#691 bugfix: incorrectly displaying first day of a week
  src/components/pages/schedule-page/calendar-section/components/date-picker/DatePicker.styles.ts
  src/components/pages/schedule-page/calendar-section/components/date-picker/DatePicker.tsx
  src/components/pages/schedule-page/calendar-section/components/mobile/buttonIcons/ButtonIcons.tsx
  src/components/pages/schedule-page/schedule-event-edit-section/schedule-form/constants/index.ts
  src/components/pages/schedule-page/schedule-event-edit-section/schedule-form/validation/index.ts
  src/components/pages/schedule-page/schedule-event-edit-section/schedule-info-card/ScheduleInfoCard.styles.tsx
  src/components/pages/schedule-page/schedule-event-edit-section/schedule-info-card/ScheduleInfoCard.tsx
  src/components/pages/schedule-page/schedule-event-edit-section/utils/prepareData.ts
  src/components/pages/schedule-page/schedule-section/components/schedule-header/ScheduleHeader.tsx
  src/components/pages/schedule-page/utils/getStringTime.ts
  src/pages/_app.tsx
  src/store/schedule/utils/getWeekByDate.ts
Labels: bugfix

#669 enhancement/unified-teacher-cards(#620)
  src/components/common/ui/cards/personal-teacher-card/PersonalTeacherCard.styles.ts
  src/components/common/ui/cards/personal-teacher-card/PersonalTeacherCard.tsx
  src/components/common/ui/cards/personal-teacher-subject-card/PersonalTeacherSubjectCard.styles.ts
  src/components/common/ui/cards/personal-teacher-subject-card/PersonalTeacherSubjectCard.tsx
  src/components/common/ui/cards/personal-teacher-subject-card/index.ts
  src/components/common/ui/cards/subject-teacher-card/SubjectTeacherCard.module.scss
  src/components/common/ui/cards/subject-teacher-card/SubjectTeacherCard.tsx
  src/components/common/ui/cards/subject-teacher-card/index.ts
  src/components/common/ui/cards/teacher-card/TeacherCard.module.scss
  src/components/common/ui/cards/teacher-card/TeacherCard.styles.ts
  src/components/common/ui/cards/teacher-card/TeacherCard.tsx
  src/components/pages/personal-teacher-subject-page/PersonalTeacherSubjectPage.tsx
  src/components/pages/search-pages/subject-teacher-search/components/SubjectTeacherSearchList.tsx
Labels: bugfix, enhancement

#692 feature/schedule-info-card-clickable-links
  src/components/pages/schedule-page/SchedulePage.styles.ts
  src/components/pages/schedule-page/SchedulePage.tsx
  src/components/pages/schedule-page/index.ts
  src/components/pages/schedule-page/schedule-event-edit-section/schedule-info-card/ScheduleInfoCard.tsx
  src/components/pages/schedule-page/schedule-event-edit-section/schedule-info-card/components/TextWithLinks.tsx
  src/components/pages/schedule-page/schedule-section/ScheduleSection.styles.ts
  src/components/pages/schedule-page/schedule-section/ScheduleSection.tsx
  src/components/pages/schedule-page/schedule-section/ScheduleSectionMobile.tsx
  src/pages/schedule/index.tsx
Labels: feature

#694 enhancement/refactor-poll-card
  src/components/common/ui/cards/poll-card/PollCard.styles.ts
  src/components/common/ui/cards/poll-card/PollCard.tsx
  src/components/common/ui/cards/poll-card/index.ts
  src/components/common/ui/cards/teacher-header-card/TeacherHeaderCard.styles.ts
  src/components/common/ui/cards/teacher-header-card/TeacherHeaderCard.tsx
  src/components/common/ui/cards/teacher-header-card/index.ts
  src/components/pages/poll-page/components/questions-list/QuestionsList.tsx
  src/components/pages/poll-page/components/questions-list/components/poll-card/PollCard.module.scss
  src/components/pages/poll-page/components/questions-list/components/teacher-header-card/TeacherHeaderCard.module.scss
  src/components/pages/poll-page/components/questions-list/components/teacher-header-card/TeacherHeaderCard.tsx
Labels: enhancement

#715 enchancement/poll-page-answers-sheet-questions-list-mui
  src/components/pages/poll-page/PollPage.module.scss
  src/components/pages/poll-page/PollPage.styles.ts
  src/components/pages/poll-page/PollPage.tsx
  src/components/pages/poll-page/components/answers-sheet/AnswerSheet.style.ts
  src/components/pages/poll-page/components/answers-sheet/AnswersSheet.module.scss
  src/components/pages/poll-page/components/answers-sheet/AnswersSheet.tsx
  src/components/pages/poll-page/components/questions-list/QuestionsList.module.scss
  src/components/pages/poll-page/components/questions-list/QuestionsList.styles.ts
  src/components/pages/poll-page/components/questions-list/QuestionsList.tsx
Labels: enhancement

#721 bugfix/change-backticks
  .eslintrc.json
  src/components/pages/about-page/AboutPage.tsx
Labels: bugfix

#726 bugfix/pollcard-click
  src/components/common/ui/cards/poll-card/PollCard.styles.ts
  src/components/common/ui/cards/poll-card/PollCard.tsx
Labels: bugfix

#727 bugfix/schedule-word-wrap
  src/components/pages/schedule-page/schedule-section/components/schedule/components/schedule-column/components/schedule-card/cards/Cards.styles.ts
Labels: bugfix

#730 Enhancement/account page mui refactor
  src/components/common/ui/form/input/index.ts
  src/components/pages/account-page/components/general-tab/GeneralTab.styles.ts
  src/components/pages/account-page/components/general-tab/components/contacts-block/components/ContactForm.tsx
  src/components/pages/account-page/components/group-tab/GroupTab.styles.ts
  src/components/pages/account-page/components/group-tab/GroupTab.tsx
  src/components/pages/account-page/components/security-tab/SecurityTab.styles.ts
  src/components/pages/account-page/components/security-tab/SecurityTab.tsx
  src/components/pages/account-page/components/security-tab/components/change-password-form/ChangePasswordForm.tsx
Labels: enhancement

#736 bugfix:fixed cards in one column
  src/components/pages/search-pages/subject-teacher-search/components/SubjectTeacherSearchList.module.scss
  src/components/pages/search-pages/subject-teacher-search/components/SubjectTeacherSearchList.styles.ts
  src/components/pages/search-pages/subject-teacher-search/components/SubjectTeacherSearchList.tsx
Labels: bugfix

#742 bugfix/button-opposite-to-the-Captain
  src/components/pages/account-page/components/group-tab/components/table/student-table/components/EditingColumn.tsx
Labels: bugfix

#740 bugfix/card-text-overflow
  src/components/pages/search-pages/subject-teacher-search/SearchTeacherPage.styles.ts
  src/components/pages/search-pages/subject-teacher-search/components/SubjectTeacherSearchList.styles.ts
Labels: bugfix

#746 bugfix/contacts-overlap
  src/components/common/ui/cards/personal-teacher-card/PersonalTeacherCard.styles.ts
Labels: bugfix

#672 enhancement/remove-pages-duplicates(#633)
  src/components/pages/email-confirmation-page/EmailConfirmationPage.module.ts
  src/components/pages/email-confirmation-page/EmailConfirmationPage.tsx
  src/components/pages/email-confirmation-page/index.ts
  src/components/pages/password-recovery/email-confirmation-page/PasswordResetEmailConfirmationPage.tsx
  src/components/pages/register/email-confirmation-page/RegistrationEmailConfirmationPage.module.scss
  src/components/pages/register/email-confirmation-page/RegistrationEmailConfirmationPage.tsx
Labels: enhancement

#752 bugfix/subject link is clicked out of text
  src/components/pages/schedule-page/schedule-event-edit-section/schedule-info-card/ScheduleInfoCard.styles.tsx
Labels: bugfix

#749 bugfix/incorrect-day-calendar
  src/components/pages/schedule-page/schedule-event-edit-section/schedule-form/components/calendar-input/CalendarInput.tsx
Labels: bugfix

#739 bugfix/floating-card
  src/components/common/ui/cards/floating-card/FloatingCard.tsx
  src/components/common/ui/cards/personal-teacher-card/PersonalTeacherCard.tsx
  src/components/pages/personal-teacher-page/personal-teacher-tabs/components/comment-tab/CommentTab.tsx
  src/components/pages/personal-teacher-subject-page/PersonalTeacherSubjectPage.tsx
Labels: bugfix
