Repository fictadvisor/fictadvisor-web, pull requests merged in 2023-08, with the labels that each got.

#609 Enhancement/Rewrite teacher search using mui
  src/components/pages/search-pages/teacher-search/TeacherSearchPage.module.scss
  src/components/pages/search-pages/teacher-search/TeacherSearchPage.styles.ts
  src/components/pages/search-pages/teacher-search/TeacherSearchPage.tsx
  src/components/pages/search-pages/teacher-search/components/TeacherSearchList.module.scss
  src/components/pages/search-pages/teacher-search/components/TeacherSearchList.styles.ts
  src/components/pages/search-pages/teacher-search/components/TeacherSearchList.tsx
Labels: enhancement

#614 Documentation/Added Story documentation for Toast component
  src/components/common/ui/toast-mui/Toast.stories.tsx
  src/components/common/ui/toast-mui/Toast.tsx
Labels: documentation

#595 enhancement/resource-card-mui
  src/components/pages/main-page/components/resource-card/ResourceCard.module.scss
  src/components/pages/main-page/components/resource-card/ResourceCard.styles.ts
  src/components/pages/main-page/components/resource-card/ResourceCard.tsx
Labels: enhancement

#596 enhancement/register-page-mui
  src/components/pages/register/register-page/RegisterImage.module.scss
  src/components/pages/register/register-page/RegisterPage.module.scss
  src/components/pages/register/register-page/RegisterPage.styles.ts
  src/components/pages/register/register-page/RegisterPage.tsx
  src/components/pages/register/register-page/components/left-block/LeftBlock.module.scss
  src/components/pages/register/register-page/components/left-block/LeftBlock.styles.ts
  src/components/pages/register/register-page/components/left-block/LeftBlock.tsx
  src/components/pages/register/register-page/components/left-block/Link.module.scss
  src/components/pages/register/register-page/components/register-form/FormStyles.module.scss
  src/components/pages/register/register-page/components/register-form/RegisterForm.styles.ts
  src/components/pages/register/register-page/components/register-form/RegisterForm.tsx
  src/components/pages/register/register-page/components/right-block/RightBlock.module.scss
  src/components/pages/register/register-page/components/right-block/RightBlock.styles.ts
  src/components/pages/register/register-page/components/right-block/RightBlock.tsx
Labels: enhancement

#604 feature/schedule-input
  src/components/pages/schedule-page/schedule-event-edit-section/components/schedule-input/ScheduleInput.styles.ts
Labels: enhancement

#618 documentation/tooltip
  src/components/common/ui/tooltip-mui/Tooltip.stories.tsx
Labels: documentation

#589 enhancement/mui-teacher-subject-card
  src/components/common/ui/cards/personal-teacher-subject-card/PersonalTeacherSubjectCard.styles.ts
  src/components/common/ui/cards/personal-teacher-subject-card/PersonalTeacherSubjectCard.tsx
  src/components/common/ui/cards/personal-teacher-subject-card/index.ts
  src/components/pages/personal-teacher-subject-page/PersonalTeacherSubjectPage.tsx
  src/components/pages/personal-teacher-subject-page/personal-teacher-subject-card/PersonalTeacherSubjectCard.module.scss
  src/components/pages/personal-teacher-subject-page/personal-teacher-subject-card/PersonalTeacherSubjectCard.tsx
  src/styles/theme/constants/typography/interfaces.ts
  src/styles/theme/constants/typography/typography.ts
Labels: enhancement

#613 feature/schedule-line
  public/icons/schedule-line.svg
  src/components/pages/schedule-page/schedule-event-edit-section/components/schedule-line/ScheduleLine.styles.ts
  src/components/pages/schedule-page/schedule-event-edit-section/components/schedule-line/ScheduleLine.tsx
  src/components/pages/schedule-page/schedule-event-edit-section/components/schedule-line/index.ts
  src/components/pages/schedule-page/schedule-event-edit-section/components/schedule-line/types/index.ts
  src/pages/test/schedule-line.tsx
Labels: feature

#630 Documentation/numbered text area story
  src/components/common/ui/form/numbered-text-area/NumberedTextArea.stories.tsx
  src/components/common/ui/form/numbered-text-area/NumberedTextArea.styles.ts
  src/components/common/ui/form/numbered-text-area/NumberedTextArea.tsx
  src/components/common/ui/form/numbered-text-area/components/LineNumbers.styles.ts
  src/components/common/ui/form/numbered-text-area/components/LineNumbers.tsx
  src/components/common/ui/form/numbered-text-area/components/index.ts
  src/components/common/ui/form/numbered-text-area/index.ts
  src/components/common/ui/form/numbered-text-area/types/index.ts
  src/components/common/ui/form/numbered-text-area/utils/index.tsx
  src/components/common/ui/form/with-formik/numbered-text-area/FormikNumberedTextArea.tsx
  src/components/common/ui/form/with-formik/numbered-text-area/index.ts
  src/components/pages/test-pages/numbered-text-area-page/NumberedTextAreaPage.tsx
Labels: enhancement, documentation

#631 feature/schedule-dropdown
  src/components/common/ui/form/dropdown/Dropdown.tsx
  src/components/common/ui/form/dropdown/components/option/Option.tsx
  src/components/common/ui/form/dropdown/types/index.ts
  src/components/pages/schedule-page/schedule-event-edit-section/components/schedule-dropdown/ScheduleDropdown.stories.tsx
  src/components/pages/schedule-page/schedule-event-edit-section/components/schedule-dropdown/ScheduleDropdown.styles.ts
  src/components/pages/schedule-page/schedule-event-edit-section/components/schedule-dropdown/ScheduleDropdown.tsx
  src/components/pages/schedule-page/schedule-event-edit-section/components/schedule-dropdown/index.ts
Labels: feature

#637 Enhancement/Refactor slider component
  src/components/common/ui/form/index.ts
  src/components/common/ui/form/slider-mui/Slider.tsx
  src/components/common/ui/form/slider-mui/const/marks.ts
  src/components/common/ui/form/slider-mui/index.ts
  src/components/common/ui/form/slider/Slider.module.scss
  src/components/common/ui/form/slider/Slider.stories.tsx
  src/components/common/ui/form/slider/Slider.styles.ts
  src/components/common/ui/form/slider/Slider.tsx
  src/components/common/ui/form/slider/const/marks.ts
  src/components/common/ui/form/slider/index.ts
  src/components/common/ui/form/slider/types/index.ts
  src/components/common/ui/form/with-formik/slider/FormikSlider.tsx
  src/components/common/ui/form/with-formik/slider/index.ts
  src/components/pages/poll-page/components/answers-sheet/AnswersSheet.tsx
Labels: enhancement, documentation

#641 documentation/text-area-sb
  src/components/common/ui/form/text-area-mui/TextArea.stories.tsx
Labels: documentation

#652 fix/trim-error-poll-page
  src/components/pages/poll-page/components/answers-sheet/AnswersSheet.tsx
Labels: bugfix
