Repository fictadvisor/fictadvisor-web, pull requests merged in 2023-10, with the labels that each got.

#690 enchancement/account-page
  src/components/common/layout/header/constants/index.tsx
  src/components/common/ui/cards/poll-teacher-card/SkipTeacherPopup.tsx
  src/components/common/ui/form/index.ts
  src/components/common/ui/pop-ups/Popup/Popup.stories.tsx
  src/components/common/ui/pop-ups/Popup/Popup.tsx
  src/components/pages/account-page/AccountPage.module.scss
  src/components/pages/account-page/AccountPage.styles.ts
  src/components/pages/account-page/AccountPage.tsx
  src/components/pages/account-page/components/general-tab/GeneralTab.module.scss
  src/components/pages/account-page/components/general-tab/GeneralTab.styles.ts
  src/components/pages/account-page/components/general-tab/GeneralTab.tsx
  src/components/pages/account-page/components/general-tab/components/change-avatar-window/ChangeAvatarWindow.styles.ts
  src/components/pages/account-page/components/general-tab/components/change-avatar-window/ChangeAvatarWindow.tsx
  src/components/pages/account-page/components/general-tab/components/change-avatar-window/components/avatar-dropzone/AvatarDropzone.styles.ts
  src/components/pages/account-page/components/general-tab/components/change-avatar-window/components/avatar-dropzone/AvatarDropzone.tsx
  src/components/pages/account-page/components/general-tab/components/change-avatar-window/components/avatar-dropzone/index.ts
  src/components/pages/account-page/components/general-tab/components/change-avatar-window/components/avatar-dropzone/utils/handleFileSelect.ts
  src/components/pages/account-page/components/general-tab/components/change-avatar-window/index.ts
  src/components/pages/account-page/components/general-tab/components/contacts-block/ContactsBlock.styles.ts
  src/components/pages/account-page/components/general-tab/components/contacts-block/ContactsBlock.tsx
  src/components/pages/account-page/components/general-tab/components/contacts-block/components/ContactForm.tsx
  src/components/pages/account-page/components/general-tab/components/contacts-block/components/ContactItem.tsx
  src/components/pages/account-page/components/general-tab/components/contacts-block/types/index.ts
  src/components/pages/account-page/components/general-tab/components/contacts-block/validation/index.ts
  src/components/pages/account-page/components/general-tab/components/personal-info/PersonalInfo.styles.ts
  src/components/pages/account-page/components/general-tab/components/personal-info/PersonalInfo.tsx
  src/components/pages/account-page/components/general-tab/components/personal-info/validation/index.ts
  src/components/pages/account-page/components/general-tab/utils/isValidFile.ts
  src/components/pages/account-page/components/group-tab/GroupTab.module.scss
  src/components/pages/account-page/components/group-tab/GroupTab.styles.ts
  src/components/pages/account-page/components/group-tab/GroupTab.tsx
  src/components/pages/account-page/components/group-tab/components/no-group-block/NoGroupBlock.module.scss
  src/components/pages/account-page/components/group-tab/components/no-group-block/NoGroupBlock.styles.ts
  src/components/pages/account-page/components/group-tab/components/no-group-block/NoGroupBlock.tsx
  src/components/pages/account-page/components/group-tab/components/numbered-text-area/NumberedTextArea.module.scss
  src/components/pages/account-page/components/group-tab/components/numbered-text-area/NumberedTextArea.tsx
  src/components/pages/account-page/components/group-tab/components/numbered-text-area/index.ts
  src/components/pages/account-page/components/group-tab/components/table/grid.styles.ts
  src/components/pages/account-page/components/group-tab/components/table/requests-table/RequestTable.styles.ts
  src/components/pages/account-page/components/group-tab/components/table/requests-table/RequestsTable.tsx
  src/components/pages/account-page/components/group-tab/components/table/student-table/StudentsTable.styles.ts
  src/components/pages/account-page/components/group-tab/components/table/student-table/StudentsTable.tsx
  src/components/pages/account-page/components/group-tab/components/table/student-table/components/EditingColumn.tsx
  src/components/pages/account-page/components/group-tab/components/table/student-table/components/MobileDropdown.style.ts
  src/components/pages/account-page/components/group-tab/components/table/student-table/components/MobileDropdown.tsx
  src/components/pages/account-page/components/group-tab/components/text-area-popup/TextAreaPopup.styles.ts
  src/components/pages/account-page/components/group-tab/components/text-area-popup/TextAreaPopup.tsx
  src/components/pages/account-page/components/security-tab/SecurityTab.module.scss
  src/components/pages/account-page/components/security-tab/SecurityTab.styles.ts
  src/components/pages/account-page/components/security-tab/SecurityTab.tsx
  src/components/pages/account-page/components/security-tab/components/change-password-form/ChangePasswordForm.styles.ts
  src/components/pages/account-page/components/security-tab/components/change-password-form/ChangePasswordForm.tsx
  src/components/pages/account-page/components/selective-tab/components/opened-selective/OpenedSelective.tsx
  src/components/pages/account-page/types/index.ts
  src/components/pages/main-page/components/token-popup/TokenPopup.tsx
  src/lib/api/user/UserAPI.ts
  src/lib/api/user/types/ChangeAvatarResponse.ts
Labels: enhancement

#770 feature/underlined header links
  src/components/common/layout/header/components/desktop-header/DesktopHeader.styles.ts
  src/components/common/layout/header/components/desktop-header/DesktopHeader.tsx
  src/components/common/layout/header/components/mobile-header/components/drawer/Drawer.styles.ts
  src/components/common/layout/header/components/mobile-header/components/drawer/Drawer.tsx
  src/components/common/ui/cards/poll-card/PollCard.styles.ts
  src/components/pages/poll-page/components/answers-sheet/AnswersSheet.tsx
  src/pages/poll/index.tsx
Labels: feature

#781 bugfix/conference link lenght
  src/components/pages/schedule-page/schedule-event-edit-section/schedule-info-card/ScheduleInfoCard.styles.tsx
  src/components/pages/schedule-page/schedule-event-edit-section/schedule-info-card/ScheduleInfoCard.tsx
Labels: bugfix

#779 bugfix/separate output of incorrect information when loggin into account
  src/components/pages/login-page/components/login-form-block/components/login-form/LoginForm.tsx
Labels: bugfix

#783 bugfix/typos-on-account-page
  src/components/pages/account-page/components/group-tab/components/text-area-popup/TextAreaPopup.tsx
  src/components/pages/account-page/components/security-tab/components/change-password-form/ChangePasswordForm.tsx
Labels: bugfix

#791 bugfix/space-between-error-and-group-input
  src/components/pages/account-page/components/group-tab/components/no-group-block/NoGroupBlock.styles.ts
  src/components/pages/account-page/components/group-tab/components/no-group-block/NoGroupBlock.tsx
Labels: bugfix

#789 budfix/student-deletion
  src/components/pages/account-page/components/group-tab/components/table/student-table/components/EditingColumn.tsx
Labels: bugfix

#790 bugfix/student-promotion
  src/components/pages/account-page/components/group-tab/components/table/student-table/components/EditingColumn.tsx
Labels: bugfix

#798 bugfix/pollcard-text
  src/components/common/ui/cards/poll-card/PollCard.styles.ts
Labels: bugfix

#815 bugfix/password-restriction-for-account
  src/components/pages/register/register-page/components/register-form/RegisterForm.tsx
Labels: bugfix

#823 bugfix/mobile-schedule-filters
  package.json
  src/components/pages/schedule-page/calendar-section/components/mobile/checkboxes-dropdown/CheckboxesDropDown.styles.ts
  src/components/pages/schedule-page/calendar-section/components/mobile/checkboxes-dropdown/constants/CheckboxConstants.ts
  yarn.lock
Labels: bugfix
