Repository fictadvisor/fictadvisor-web, pull requests merged in 2023-05, with the labels that each got.

#322 feature/line-graph
  src/components/common/ui/line_graph/LineGraph.styles.ts
  src/components/common/ui/line_graph/LineGraph.tsx
  src/components/common/ui/line_graph/index.ts
  src/components/common/ui/line_graph/utils/constrants.ts
  src/components/common/ui/line_graph/utils/utils.ts
  src/components/pages/test-pages/line-graph-page/LineGraph.styles.ts
  src/components/pages/test-pages/line-graph-page/LineGraphPage.tsx
  src/components/pages/test-pages/line-graph-page/index.ts
  src/pages/test/line-graph.tsx
Labels: feature

#331 fix/email-case
  src/components/pages/login-page/components/login-form/LoginForm.tsx
  src/components/pages/password-recovery/email-confirmation-page/PasswordResetEmailConfirmationPage.tsx
  src/components/pages/password-recovery/forgot-password-page/components/forgot-password-form/ForgotPasswordForm.tsx
  src/components/pages/register/register-page/components/register-form/utils/index.ts
Labels: bugfix

#326 feature/comment
  src/components/common/ui/comment/Comment.styles.ts
  src/components/common/ui/comment/Comment.tsx
  src/components/common/ui/comment/index.ts
  src/components/pages/test-pages/comment-page/CommentTestPage.styles.ts
  src/components/pages/test-pages/comment-page/CommentTestPage.tsx
  src/components/pages/test-pages/comment-page/index.ts
  src/pages/test/comment.tsx
  yarn.lock
Labels: feature

#328 enhancement/rating
  public/assets/stars-full.svg
  src/components/common/ui/rating-mui/Rating.tsx
  src/components/common/ui/rating-mui/index.ts
  src/components/pages/test-pages/rating-page/RatingTestPage.styles.ts
  src/components/pages/test-pages/rating-page/RatingTestPage.tsx
  src/components/pages/test-pages/rating-page/index.ts
  src/pages/test/rating.tsx
Labels: enhancement

#327 Feature/column chart
  package.json
  src/components/common/ui/column-chart/ColumnChart.styles.ts
  src/components/common/ui/column-chart/ColumnChart.tsx
  src/components/common/ui/column-chart/index.ts
  src/components/common/ui/column-chart/utils/data.ts
  src/components/common/ui/column-chart/utils/options.ts
  src/components/pages/test-pages/column-chart-page/ColumnChartTestPage.styles.ts
  src/components/pages/test-pages/column-chart-page/ColumnChartTestPage.tsx
  src/components/pages/test-pages/column-chart-page/index.ts
  src/lib/api/teacher/dto/GetTeacherEvaluationsDTO.ts
  src/pages/test/column-chart.tsx
  yarn.lock
Labels: feature
